[package]
name = "envfile"
version = "0.1.0"
authors = ["gyara <me@gyara.moe>"]
edition = "2018"

[dependencies.serde]
version = "1.0.104"
features = ["derive"]

[dependencies.async-std]
version = "1.4.0"
features = ["attributes"]
